site_name: NLSE Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
  - mkdocs-jupyter:
      execute: false
      kernel_name: python3

nav:
  - Home: index.md
  - Getting started:
      - Installation: "installation.md"
      - Basic Usage: "basic_usage.md"

      - Structure and Inheritance: "structure_and_inheritance.md"
      - Contributing: "contributing.md"
  - Tutorial:
      - What is the Physics problem ?: "physics_problem.md"
      - A NLSE tutorial: "nlse_tutorial.ipynb"
  - How to:
      - How to ?: "how_to.md"
  - Reference:
      - NLSE: nlse.md
      - 1D NLSE : nlse_1d.md
      - 3D NLSE : nlse_3d.md
      - Coupled NLSE: cnlse.md
      - 1D Coupled NLSE: cnlse_1d.md
      - GPE: gpe.md
      - Driven dissipative GPE: ddgpe.md
      - Kernels: kernels.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
