on: [push]

jobs:
  tests:
    runs-on: ubuntu-lastest
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get install -y ocl-icd-opencl-dev
          sudo apt-get install -y pocl-opencl-icd
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Test with pytest
        run: |
          pip install pytest 
          pytest tests
    